#%RAML 1.0
title: American flights api
version: v1.0
traits:
  client-id-required:
      headers:
       client_id:
        type: string
       client_sceret:
        type: string  
types:
  American-flight: !include flightsType.raml           

/flights:
  get:
    is: [client-id-required]  
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
          - CLE
    responses:
      200:
        body:
          application/json:
            example:
              output: !include examples/Americanflightsexample.raml
                  
  post:
    body:
      application/json:
        type: American-flight
        examples: !include examples/AmericanflightsNoIdexample.raml         
    responses:
      201:
        body: 
          application/json:
            example: 
              message: Flight added (but not really)
/{id}:
  is: [client-id-required]
  get:
    responses:
      200:
       body:
        application/json:
          type: [American-flight]
          examples: !include examples/Americanflightsexample.raml
  delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Flight deleted (but not really)       
  
  put:
    body:
      application/json:
        type: American-flight
        examples: 
            input: !include examples/AmericanflightsNoIdexample.raml              
    responses:
        200:
          body:
            application/json:
              example:
                message: Flight updated (but not really)        
                            